import './js/slick';
import './js/slick-res';
import './js/menu';
import './js/modal-table';
import './js/modal-price';
import './js/modal-room';
import './js/modal-table-hero';
import './js/modal-table-page-rest-menu';
import './js/modal-price-page-hotel-hero';
